### ISSUE TITLE
"onVisibleBehindCanceled" is deprecated in Android O

### ISSUE THREAD

**Issue by strooonger** [stefanmedack/cccTV#8]
Hi,

I notice the file "ExoPlayerActivity.kt" overrides "onVisibleBehindCanceled", which is deprecated in Android O ([link](https://developer.android.com/reference/android/app/Activity.html)). As the official document says, "onVisibleBehindCanceled" cannot get chance to execute since Android O and will be removed in the future release.

So you may prevent putting some important operations in it. 

Hope the information can help you. :)

**Comment by stefanmedack** [comment]
Hi,

thank you for the hint. I saw that myself, but copied it from another project in order to make Amazon happy during 34C3. Luckily, I found another way to resolve problems the Amazon testers were having with the App. On develop it is already gone and as far as I remember it is also gone since the stable 2.0.0 release.

**Comment by strooonger** [comment]
👍
