### ISSUE TITLE
Improving discoverability by adding a per-congress-overview

### ISSUE THREAD

**Issue by AndreasGB** [stefanmedack/cccTV#9]
The current layout to browse for talks somewhat hinders discoverability, since there are only ever 3 shown on the screen at one time, wasting a lot of space and requiring a lot of scrolling.

I would like to propose splitting the View into two, one which is an overview over the available congresses, the other then being a 'detail' view, which then contains the videos arranged in a 2D grid, so that more can be shown on the screen at any time and browsing is faster since pressing down navigates four talks farther than just one when pressing right in the current way.

I don't know if the project is open to outside contributions, but if you like the idea, I could try to implement it in coordination with you.

**Comment by stefanmedack** [comment]
Hi Andreas,

there was quite some feedback on this topic and I am aware of it. I am already working on improving the entire discoverability today. The solution you propose is most likely what I will end up with. Since I am right in the middle, I guess it is hard to join the reworking at this stage. It will also lead to major changes through a lot of layers. 

Besides that, I would gladly take help from the outside :) I will try to add the feedback and TODOs I have on my google keep list as issues here the next days. It is awesome, that you want to help. You could either wait for the issues/improvements and pick one or you could send me a DM on twitter (@zonic03) right now and I can tell you briefly what's planned next.

**Comment by stefanmedack** [comment]
Version 2.1.0 should probably fix everything you were proposing @AndreasGB. Thank you for the feedback. If you have more ideas to this story or other improvements in mind do not hesitate to file a bug or create a pull request.
Also, I started adding some issues on other bugs/improvements, in case you still would like to help out.
